version: '2'
services:
    leboncoinimmoscrapper-app:
        image: leboncoinimmoscrapper
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://leboncoinimmoscrapper-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=leboncoinImmoScrapper
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://leboncoinimmoscrapper-elasticsearch:9200
    leboncoinimmoscrapper-mongodb:
        extends:
            file: mongodb.yml
            service: leboncoinimmoscrapper-mongodb
    leboncoinimmoscrapper-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: leboncoinimmoscrapper-elasticsearch
